#!/bin/bash
# Copyright (C) 2010 Tomasz Dlugosz <tomek3d@gmail.com>
#
# Distributed under the terms of the GNU General Public License v3
#
# based on sciagnijpbi.sh and sciagnijpbijpg.sh by raf_k <at> wp.pl

TMPDIR=$(mktemp -d)

if [ -z $1 ] ; then
	echo "Nie podales id ksiazki. Bez id nic nie sciagne."
	echo "Wejdz na strone www.pbi.edu.pl ,"
	echo "otworz interesujaca Cie pozycje i znajdz w adresie"
	echo '?p=XXXX np.'
	echo 'http://www.pbi.edu.pl/content.php?p=50620&s=2&w='
	echo
	echo "Spis id jest rowniez w dolaczonym do skryptu katalogu"
	echo -ne "\nPodaj id ksiazki, lub zero, by wyjsc: "
	read BOOKID
	if [ "$BOOKID" == "0" ] ; then
		exit 1
	fi
else
	BOOKID=$1;
fi

# check if given id is a number
if echo $BOOKID | grep "^[0-9]*$">/dev/null; then
	echo "id ksiazki $BOOKID"
else
	echo "niepoprawne id ksiazki!"
	exit 1
fi

wget -O"$TMPDIR/cover.html" "http://www.pbi.edu.pl/left_1.php?p=$BOOKID&s=&w=" 2>/dev/null

# check number of pages
PAGENO=`cat $TMPDIR/cover.html | grep "var pages"|tr ";" " "| cut -d" " -f4`
# check number digits needed
DIGITS=`echo "$PAGENO" |wc -L`

# check author and title
TYTUL=`grep '<TD class=t11-red><STRONG>' $TMPDIR/cover.html |tr "<>" "||"| cut -d"|" -f5 | sed 's/[ \t]*$//'`
AUTOR=`grep "<TD class=t11-red>" $TMPDIR/cover.html |tail -n1|tr "<>" "||"| cut -d"|" -f3 | sed 's/[ \t]*$//'`
if [ "$AUTOR" == "-" ] ; then
	AUTOR="Autor nie podany"
fi
echo -e "\n[33mZnalazlem ksiazke:[0m"
echo -e " Autor: $AUTOR \n Tytul: $TYTUL\n"
rm -f "${TMPDIR}/cover.html"

# check whether book is in HTML or images
PAGECOUNT=1
TEST=`wget -O- "http://www.pbi.edu.pl/content.php?p=${BOOKID}&s=${PAGECOUNT}" 2>/dev/null |grep 'id=imgview'`
if [ "$TEST" != "" ] ; then
	echo "pliki graficzne"
	JPGPATH=`echo $TEST|sed 's/.*src="\(.*\)-.*/\1/'`
	while [ $PAGECOUNT -le $PAGENO ] ; do
		printf "\rSciagam strone $PAGECOUNT / $PAGENO "
		JPGABSPATH=`printf "http://www.pbi.edu.pl/${JPGPATH}-%06d.jpg" $PAGECOUNT`
		TARGETFILE=`echo $PAGECOUNT|awk {'printf "%0'${DIGITS}'d",$1'}`
		wget -O "${TMPDIR}/${TARGETFILE}.jpg" $JPGABSPATH 2>/dev/null
		PAGECOUNT=`expr $PAGECOUNT + 1`
	done
	echo -e "[32m[ok][0m"

	OUTDIR="${AUTOR} - ${TYTUL}"
	mv -- "$TMPDIR" "${OUTDIR}"
	echo -e "[33mPliki zapisano w katalogu:[0m ${OUTDIR}"
else
	echo "pliki tekstowe"
	while [ $PAGECOUNT -le $PAGENO ] ; do
		source="http://www.pbi.edu.pl/content.php?p=${BOOKID}&s=${PAGECOUNT}&w="
		TARGETFILE=`echo $PAGECOUNT|awk {'printf "%0'${DIGITS}'d",$1'}`
		echo -ne "\rSciagam strone $PAGECOUNT / $PAGENO "
		wget -O"${TMPDIR}/${TARGETFILE}.html" "$source" 2>/dev/null
		PAGECOUNT=`expr $PAGECOUNT + 1`
	done

	echo -ne "[32m[ok][0m\nLacze pliki"

	OUTPUT="${AUTOR} - ${TYTUL}.htm"

	echo -e '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">\n<html>\n<head>\n<title>'${AUTOR} - ${TYTUL}'</title>\n<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">\n</head>\n<body>' >"${OUTPUT}"

	for i in `ls -1 ${TMPDIR}/[0-9]*.html`; do
		awk '/class=\"txt\"/ { print $0 }' $i >>"${OUTPUT}"
	done
	echo -e '</body>\n</html>' >>"${OUTPUT}"
	echo -ne " [32m[ok][0m\nPoprawiam formatowanie"
	sed -e 's/^[ \t]*<style.*<\/style>//' \
		-e 's/ >/>/g' \
		-e 's/ style="font-size: 100%" class="txt"//g' \
		-e 's/<span>\([[:alnum:] ,.?!-—;]*\)<\/span>/\1/g' \
		-e 's/<span><i>\([[:alnum:] ,.?!-—;]*\)<\/i><\/span>/<i>\1<\/i>/g' \
		-i "$OUTPUT"
	echo -e "[32m [ok][0m \n\n[33mZapisano plik:[0m $OUTPUT"
	rm -fr "$TMPDIR"
fi

