#!/bin/bash
# Copyright (C) 2010 Tomasz Dlugosz <tomek3d@gmail.com>
#
# Distributed under the terms of the GNU General Public License v3
#
# based on sciagnijpbi.sh and sciagnijpbijpg.sh by raf_k <at> wp.pl

TMPDIR=$(mktemp -d)

getget() {
wget -o $TMPDIR/log.tmp -O"$TMPDIR/$2.html" "$1" &
pid=$!

i=1
while [ $i -eq 1 ] ; do
  ps -p $pid >/dev/null
  i=$?;
  sleep 1
done
}

if [ -z $1 ] ; then
 echo "Nie podales id ksiazki, bez tego nic nie sciagne, wejdz na strone"
 echo "www.pbi.edu.pl otworz interesujaca cie pozycje, szukaj w adresie"
 echo '?p=XXXX np. echo http://www.pbi.edu.pl/content.php?p=50620&s=2&w='
 echo "Spis id jest rowniez w dolaczonym do skryptu katalogu"
 echo "Np. zeby sciagnac obrone Sokratesa nalezy wpisac sh sciagnijpbi.sh 1896"
 exit 1
else
 bookid=$1;
fi

getget "http://www.pbi.edu.pl/left_1.php?p=$bookid&s=&w=" cover

# check number of pages
ii=`cat $TMPDIR/cover.html | grep "var pages"|tr ";" " "| cut -d" " -f4`
dec=`echo "$ii" |wc -L`

# check author and title
tytul=`grep '<TD class=t11-red><STRONG>' $TMPDIR/cover.html |tr "<>" "||"| cut -d"|" -f5 | sed 's/[ \t]*$//'`
autor=`grep "<TD class=t11-red>" $TMPDIR/cover.html |tail -n1|tr "<>" "||"| cut -d"|" -f3 | sed 's/[ \t]*$//'`
echo -e "\n[33mZnalazlem ksiazke:[0m"
echo -e " Autor: $autor \n Tytul: $tytul\n"

# check whether book is in HTML or images
page=1
TEST=`wget -O- "http://www.pbi.edu.pl/content.php?p=${bookid}&s=${page}" 2>/dev/null |grep 'id=imgview'`
if [ "$TEST" != "" ] ; then
	echo "pliki graficzne"
	scrpattern=`echo $TEST|sed 's/.*src="\(.*\)-.*/\1/'`
	while [ $page -le $ii ] ; do
		printf "\rSciagam strone $page / $ii "
		scrsrc=`printf "http://www.pbi.edu.pl/${scrpattern}-%06d.jpg" $page`
		file=`echo $page|awk {'printf "%0'${dec}'d",$1'}`
		wget -O "${TMPDIR}/${file}.jpg" $scrsrc 2>/dev/null
		page=`expr $page + 1`
	done
	echo -e "[32m[ok][0m"

	OUTDIR="${autor} - ${tytul}"
	mv -- "$TMPDIR" "${OUTDIR}"
	echo -e "[33mPliki zapisano w katalogu:[0m ${OUTDIR}"
else
	echo "pliki tekstowe"
	while [ $page -le $ii ] ; do
		source="http://www.pbi.edu.pl/content.php?p=${bookid}&s=${page}&w="
		file=`echo $page|awk {'printf "%0'${dec}'d",$1'}`
		echo -ne "\rSciagam strone $page / $ii "
		getget $source $file 
		page=`expr $page + 1`
	done

	echo -ne "[32m[ok][0m\nLacze pliki"

	outputfile="${autor} - ${tytul}.htm"

	echo -e '<html>\n<head>\n<title>Polska Biblioteka Internetowa</title>\n<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">\n</head>\n<body>' >"${outputfile}"

	for i in `ls -1 ${TMPDIR}/[0-9]*.html`; do
		awk '/class=\"txt\"/ { print $0 }' $i >>"${outputfile}"
	done
	echo -e '</body>\n</html>' >>"${outputfile}"
	echo -e "[32m [ok][0m \n\n[33mZapisano plik:[0m $outputfile"
	rm -fr "$TMPDIR"
fi

